import http from "node:http";
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";

const port = Number(process.env.BRANDMASTER_ENRICHMENT_PORT || 8791);
const root = path.resolve(process.env.BRANDMASTER_ENRICHMENT_DATA || "enrichment-service/data");
const dbPath = path.join(root, "jobs.json");
let db = { jobs: [], candidates: [] };
await fs.mkdir(root, { recursive: true });
try { db = JSON.parse(await fs.readFile(dbPath, "utf8")); } catch {}
const save = () => fs.writeFile(dbPath, JSON.stringify(db, null, 2));
const json = (res, code, value) => { res.writeHead(code, { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" }); res.end(JSON.stringify(value)); };
const body = async (req) => { let text = ""; for await (const chunk of req) text += chunk; return text ? JSON.parse(text) : {}; };
const clean = (value) => String(value || "").normalize("NFKC").replace(/[\u200B-\u200D\uFEFF]/g, "").replace(/\s+/g, " ").trim();
const norm = (value) => clean(value).toLowerCase().replace(/[^\p{L}\p{N}]+/gu, " ").trim();
const title = (value) => clean(value).toLowerCase().replace(/(^|[\s-])\p{L}/gu, (m) => m.toUpperCase());
function csv(text) { const rows=[]; let row=[], value="", quoted=false; for(let i=0;i<text.length;i++){const c=text[i]; if(quoted){if(c==='"'&&text[i+1]==='"'){value+='"';i++;}else if(c==='"')quoted=false;else value+=c;} else if(c==='"')quoted=true; else if(c===','){row.push(value);value="";} else if(c==='\n'){row.push(value);rows.push(row);row=[];value="";} else if(c!=='\r')value+=c;} if(value||row.length){row.push(value);rows.push(row);} const headers=rows.shift().map((x)=>clean(x).toLowerCase()); return rows.map((r)=>Object.fromEntries(headers.map((h,i)=>[h,clean(r[i])]))); }
function aliases(row){ return String(row.aliases || "").split(",").map(clean).filter(Boolean); }
function recommendation(row, allNames) { const name=clean(row.name || row.brandname); const canonical=title(name); const originalAliases=aliases(row); const nextAliases=[...new Set(originalAliases.filter((a)=>norm(a)&&norm(a)!==norm(name)&&a.length<80))]; const reasons=[]; if(canonical!==name) reasons.push("Normalize casing, spacing, or invisible characters"); const unrelated=nextAliases.filter((a)=>{const akey=norm(a), nkey=norm(name); return akey && akey!==nkey && !akey.includes(nkey) && !nkey.includes(akey) && a.split(/\s+/).length<=3;}); if(unrelated.length) reasons.push("Alias does not resemble the canonical brand and requires evidence"); if(allNames.has(norm(name))) reasons.push("Canonical name is duplicated after normalization"); const changed=canonical!==name || nextAliases.join("|")!==originalAliases.join("|"); return { suggestedName:canonical, suggestedAliases:nextAliases, removedAliases:originalAliases.filter((a)=>!nextAliases.includes(a)), reasons, confidence: reasons.some((r)=>r.includes("requires evidence"))?0.55:changed?0.9:1, status:changed?"REVIEW":"NO_CHANGE" }; }
async function run(job){ job.status="RUNNING"; await save(); const text=await fs.readFile(job.inputPath,"utf8"); const rows=csv(text); const names=new Set(rows.map((r)=>norm(r.name||r.brandname)).filter(Boolean)); for(let i=0;i<rows.length;i+=job.batchSize){ const batch=rows.slice(i,i+job.batchSize); for(const row of batch){const id=row.id||row.brandid||row.brandid; if(!id) continue; const rec=recommendation(row,names); if(rec.status!=="NO_CHANGE") db.candidates.push({id:crypto.randomUUID(),jobId:job.id,brandId:id,currentName:row.name||row.brandname,currentAliases:aliases(row),...rec,decision:"PENDING",evidence:[]});} job.processed=Math.min(rows.length,i+batch.length); await save(); await new Promise((r)=>setImmediate(r)); } job.status="COMPLETED"; job.completedAt=new Date().toISOString(); await save(); }
const server=http.createServer(async(req,res)=>{ if(req.method==="OPTIONS"){res.writeHead(204,{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type"});return res.end();} try { const url=new URL(req.url,`http://${req.headers.host}`); if(req.method==="GET"&&url.pathname==="/health")return json(res,200,{ok:true,service:"brandmaster-enrichment",port}); if(req.method==="GET"&&url.pathname==="/jobs")return json(res,200,{jobs:db.jobs}); if(req.method==="GET"&&url.pathname.startsWith("/jobs/")){const job=db.jobs.find((x)=>x.id===url.pathname.split("/")[2]);return job?json(res,200,{job,candidates:db.candidates.filter((x)=>x.jobId===job.id)}):json(res,404,{error:"Job not found"});} if(req.method==="POST"&&url.pathname==="/jobs"){const input=(await body(req)).inputPath; if(!input) return json(res,400,{error:"inputPath is required"}); const job={id:crypto.randomUUID(),inputPath:path.resolve(input),batchSize:100,status:"QUEUED",processed:0,createdAt:new Date().toISOString()}; db.jobs.unshift(job); await save(); void run(job).catch(async(error)=>{job.status="FAILED";job.error=String(error.message||error);await save();}); return json(res,202,{job});} if(req.method==="PATCH"&&url.pathname.startsWith("/candidates/")){const candidate=db.candidates.find((x)=>x.id===url.pathname.split("/")[2]); if(!candidate)return json(res,404,{error:"Candidate not found"}); Object.assign(candidate,await body(req)); await save(); return json(res,200,{candidate});} if(req.method==="POST"&&url.pathname.startsWith("/jobs/")&&url.pathname.endsWith("/export")){const job=db.jobs.find((x)=>x.id===url.pathname.split("/")[2]); if(!job)return json(res,404,{error:"Job not found"}); const approved=db.candidates.filter((x)=>x.jobId===job.id&&x.decision==="APPROVE"); const output=path.join(root,`root-enriched-${job.id}.json`); await fs.writeFile(output,JSON.stringify({schemaVersion:"brandmaster.root-enrichment.v1",generatedAt:new Date().toISOString(),jobId:job.id,candidates:approved},null,2)); return json(res,200,{output,count:approved.length});} return json(res,404,{error:"Not found"}); } catch(error){return json(res,500,{error:String(error.message||error)});} });
server.listen(port,"127.0.0.1",()=>console.log(`Brandmaster enrichment service listening on http://127.0.0.1:${port}`));
